Fix compile error of missing proguard.flags
BZ: 4373

When I upload some patches (20172) for Recovery OS, it reported a compile error:
Error: /home/umgbuild/data/buildbot/workdir/workdir/hardware/intel/
unipoint/UnipointAPIExampleAPP/proguard.flags (No such file or directory).

Signed-off-by: lwan89x <liangx.wang@intel.com>

Change-Id: I28da431f668e98f497f3331b0616e4256c5e84ac
Reviewed-on: http://android.intel.com:8080/20301
Reviewed-by: Qin, Xiaokang <xiaokang.qin@intel.com>
Tested-by: Qin, Xiaokang <xiaokang.qin@intel.com>
Reviewed-by: Shi, Lirong <lirong.shi@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>